1. clean the data(outlier,missing values,type conversion)
2. What is the mean value of sepal length
3. sort the sepal width in ascending order.
4. apply all statistical measures on  sepal width and length
5. after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values

In [1]:
import numpy as np

In [2]:
iris = np.genfromtxt(r"C:\Users\Admin\Downloads\Iris_clean_-_Copy.csv",dtype = 'float32', delimiter = ',')
iris

array([[      nan,       nan,       nan,       nan],
       [5.100e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.700e+00, 3.200e+00, 1.300e+00, 2.000e-01],
       [4.600e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.400e+00,       nan, 1.700e+00, 4.000e-01],
       [4.600e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.400e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.100e+00,       nan, 1.000e-01],
       [5.400e+00, 3.700e+00, 1.500e+00, 2.000e-01],
       [4.800e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.800e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.300e+00, 3.000e+00, 1.100e+00, 1.000e-01],
       [5.800e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.700e+00, 4.400e+00, 1.500e+00, 4.000e-01],
       [5.040e+01,       nan, 1.300e+00, 4.000e-01],
       [5.100e+00, 3.500e+00, 1.400e+00, 3.000

In [3]:
sepal_len = iris[1:,0] # sepal length
sepal_len

array([  5.1,   4.9,   4.7,   4.6,  50. ,   5.4,   4.6,   5. ,   4.4,
         4.9,   5.4,   4.8,   4.8,   4.3,   5.8,   5.7,  50.4,   5.1,
         5.7,   5.1,   5.4,   5.1,   4.6,   5.1,   4.8,   5. ,   5. ,
         5.2,   5.2,   4.7,   4.8,   5.4,   5.2,   5.5,   4.9,   5. ,
         5.5,   4.9,   4.4,   5.1,   5. ,   4.5,   4.4,   5. ,   5.1,
         4.8,   5.1,   4.6,   5.3,   5. ,   7. ,   6.4,   6.9,   5.5,
         6.5,   5.7, 116.3,   4.9,   6.6,   5.2,   5. ,   5.9,   6. ,
         6.1,   5.6,   6.7,   5.6,   5.8,   6.2,   5.6,   5.9,   6.1,
         6.3,   6.1,   6.4,   6.6,   6.8,   6.7,   6. ,   5.7,   5.5,
         5.5,   5.8,   6. ,   5.4,   6. ,   6.7,   6.3,   5.6,   5.5,
         5.5,   6.1,   5.8,   5. ,   5.6,   5.7,   5.7,   6.2,   5.1,
         5.7,   6.3,   5.8,   7.1,   6.3,   6.5,   7.6,   4.9,   7.3,
         6.7,   7.2,   6.5,   6.4,   6.8,   5.7,   5.8,   6.4,   6.5,
         7.7,   7.7,   6. ,   6.9,   5.6,   7.7,   6.3,   6.7,   7.2,
         6.2,   6.1,

In [4]:
sepal_len = np.where(sepal_len>=50,2,sepal_len)
sepal_len

array([5.1, 4.9, 4.7, 4.6, 2. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 2. , 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 2. , 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 2. ,
       nan, nan, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9, 5.6, 7.7, nan, nan, 7.2, 4.9,
       7.3, 6.7, 5.9, 5.6, 7.7, 6.3, 7.2, 6.5, 6.4], dtype=float32)

In [5]:
sepal_len = np.where(sepal_len==-1,np.nan,sepal_len)
sepal_len

array([5.1, 4.9, 4.7, 4.6, 2. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 2. , 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 2. , 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 2. ,
       nan, nan, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9, 5.6, 7.7, nan, nan, 7.2, 4.9,
       7.3, 6.7, 5.9, 5.6, 7.7, 6.3, 7.2, 6.5, 6.4], dtype=float32)

In [6]:
med = np.nanmedian(sepal_len)
med

5.8

In [7]:
sepal_len = np.where(np.isnan(sepal_len),med,sepal_len)
sepal_len

array([5.1, 4.9, 4.7, 4.6, 2. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 2. , 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 2. , 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 2. ,
       5.8, 5.8, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9, 5.6, 7.7, 5.8, 5.8, 7.2, 4.9,
       7.3, 6.7, 5.9, 5.6, 7.7, 6.3, 7.2, 6.5, 6.4], dtype=float32)

In [8]:
sepal_l = sepal_len.dtype = 'float32'
sepal_l

'float32'

sepal_width

In [9]:
sepal_wid = iris[1:,1] # sepal width
sepal_wid

array([  3.5,   3. ,   3.2,   3.1,   3.6,   nan,   3.4,   3.4,   2.9,
         3.1,   3.7,   3.4, 130. ,   3. ,   4. ,   4.4,   nan,   3.5,
         3.8,   3.8,   3.4,   3.7,   3.6,   3.3,   3.4,   3. ,  34. ,
         3.5,   3.4,   3.2,   3.1,   3.4,   4.1,   4.2,   3.1,   3.2,
         3.5,   3.1,   3. ,   3.4,   3.5,   2.3,   3.2,   3.5,   3.8,
         3. ,   3.8,   3.2,   3.7,   3.3,   3.2,   3.2,   nan,   2.3,
         2.8,   2.8,   3.3,   2.4,   2.9,   2.7,   2. ,   3. ,   2.2,
         2.9,   2.9,   3.1,   3. ,   2.7,   2.2,   2.5,   3.2,   2.8,
         2.5,   nan,   2.9,   3. ,   2.8,   3. ,   2.9,   2.6,   2.4,
         2.4,   2.7,   2.7,   3. ,   3.4,   3.1,   2.3,   3. ,   2.5,
         2.6,   3. , 112.6,   2.3,   2.7,   3. ,   2.9,   2.9,   2.5,
         2.8,   3.3,   2.7,   3. ,   2.9,   3. ,   3. ,   2.5,   2.9,
         2.5,   3.6,   3.2,   2.7,   3. ,   2.5,   2.8,   3.2,   3. ,
         3.8,   2.6,   2.2,   3.2,   2.8,   2.8,   2.7,   3.3,   3.2,
         2.8,   3. ,

In [10]:
sepal_wid = np.where(sepal_wid>=40,3,sepal_wid)
sepal_wid

array([ 3.5,  3. ,  3.2,  3.1,  3.6,  nan,  3.4,  3.4,  2.9,  3.1,  3.7,
        3.4,  3. ,  3. ,  4. ,  4.4,  nan,  3.5,  3.8,  3.8,  3.4,  3.7,
        3.6,  3.3,  3.4,  3. , 34. ,  3.5,  3.4,  3.2,  3.1,  3.4,  4.1,
        4.2,  3.1,  3.2,  3.5,  3.1,  3. ,  3.4,  3.5,  2.3,  3.2,  3.5,
        3.8,  3. ,  3.8,  3.2,  3.7,  3.3,  3.2,  3.2,  nan,  2.3,  2.8,
        2.8,  3.3,  2.4,  2.9,  2.7,  2. ,  3. ,  2.2,  2.9,  2.9,  3.1,
        3. ,  2.7,  2.2,  2.5,  3.2,  2.8,  2.5,  nan,  2.9,  3. ,  2.8,
        3. ,  2.9,  2.6,  2.4,  2.4,  2.7,  2.7,  3. ,  3.4,  3.1,  2.3,
        3. ,  2.5,  2.6,  3. ,  3. ,  2.3,  2.7,  3. ,  2.9,  2.9,  2.5,
        2.8,  3.3,  2.7,  3. ,  2.9,  3. ,  3. ,  2.5,  2.9,  2.5,  3.6,
        3.2,  2.7,  3. ,  2.5,  2.8,  3.2,  3. ,  3.8,  2.6,  2.2,  3.2,
        2.8,  2.8,  2.7,  3.3,  3.2,  2.8,  3. ,  2.8,  3. ,  2.8,  3.8,
        2.8,  2.8,  2.6,  3. ,  3.4,  nan,  3. ,  3.1,  3.1,  3.1,  2.7,
        3.2,  3.3,  nan,  2.5,  3. ,  3.4,  3. ,  2

In [11]:
sepal_wid = np.where(sepal_wid==-1,np.nan,sepal_wid)
sepal_wid

array([ 3.5,  3. ,  3.2,  3.1,  3.6,  nan,  3.4,  3.4,  2.9,  3.1,  3.7,
        3.4,  3. ,  3. ,  4. ,  4.4,  nan,  3.5,  3.8,  3.8,  3.4,  3.7,
        3.6,  3.3,  3.4,  3. , 34. ,  3.5,  3.4,  3.2,  3.1,  3.4,  4.1,
        4.2,  3.1,  3.2,  3.5,  3.1,  3. ,  3.4,  3.5,  2.3,  3.2,  3.5,
        3.8,  3. ,  3.8,  3.2,  3.7,  3.3,  3.2,  3.2,  nan,  2.3,  2.8,
        2.8,  3.3,  2.4,  2.9,  2.7,  2. ,  3. ,  2.2,  2.9,  2.9,  3.1,
        3. ,  2.7,  2.2,  2.5,  3.2,  2.8,  2.5,  nan,  2.9,  3. ,  2.8,
        3. ,  2.9,  2.6,  2.4,  2.4,  2.7,  2.7,  3. ,  3.4,  3.1,  2.3,
        3. ,  2.5,  2.6,  3. ,  3. ,  2.3,  2.7,  3. ,  2.9,  2.9,  2.5,
        2.8,  3.3,  2.7,  3. ,  2.9,  3. ,  3. ,  2.5,  2.9,  2.5,  3.6,
        3.2,  2.7,  3. ,  2.5,  2.8,  3.2,  3. ,  3.8,  2.6,  2.2,  3.2,
        2.8,  2.8,  2.7,  3.3,  3.2,  2.8,  3. ,  2.8,  3. ,  2.8,  3.8,
        2.8,  2.8,  2.6,  3. ,  3.4,  nan,  3. ,  3.1,  3.1,  3.1,  2.7,
        3.2,  3.3,  nan,  2.5,  3. ,  3.4,  3. ,  2

In [12]:
med1 = np.nanmedian(sepal_wid)
med1

3.0

In [13]:
sepal_wid = np.where(np.isnan(sepal_wid),med1,sepal_wid)
sepal_wid

array([ 3.5,  3. ,  3.2,  3.1,  3.6,  3. ,  3.4,  3.4,  2.9,  3.1,  3.7,
        3.4,  3. ,  3. ,  4. ,  4.4,  3. ,  3.5,  3.8,  3.8,  3.4,  3.7,
        3.6,  3.3,  3.4,  3. , 34. ,  3.5,  3.4,  3.2,  3.1,  3.4,  4.1,
        4.2,  3.1,  3.2,  3.5,  3.1,  3. ,  3.4,  3.5,  2.3,  3.2,  3.5,
        3.8,  3. ,  3.8,  3.2,  3.7,  3.3,  3.2,  3.2,  3. ,  2.3,  2.8,
        2.8,  3.3,  2.4,  2.9,  2.7,  2. ,  3. ,  2.2,  2.9,  2.9,  3.1,
        3. ,  2.7,  2.2,  2.5,  3.2,  2.8,  2.5,  3. ,  2.9,  3. ,  2.8,
        3. ,  2.9,  2.6,  2.4,  2.4,  2.7,  2.7,  3. ,  3.4,  3.1,  2.3,
        3. ,  2.5,  2.6,  3. ,  3. ,  2.3,  2.7,  3. ,  2.9,  2.9,  2.5,
        2.8,  3.3,  2.7,  3. ,  2.9,  3. ,  3. ,  2.5,  2.9,  2.5,  3.6,
        3.2,  2.7,  3. ,  2.5,  2.8,  3.2,  3. ,  3.8,  2.6,  2.2,  3.2,
        2.8,  2.8,  2.7,  3.3,  3.2,  2.8,  3. ,  2.8,  3. ,  2.8,  3.8,
        2.8,  2.8,  2.6,  3. ,  3.4,  3. ,  3. ,  3.1,  3.1,  3.1,  2.7,
        3.2,  3.3,  3. ,  2.5,  3. ,  3.4,  3. ,  2

In [14]:
sepal_wid.dtype

dtype('float32')

petal length

In [15]:
petal_len = iris[1:,2]
petal_len

array([ 1.4,  1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  nan,  1.5,
        1.6,  1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,  1.5,
        1. ,  1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,  1.5,
        1.4,  1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3, 13. ,  1.3,  1.6,
        1.9,  1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,  4.6,
        4.5,  4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,  4.4,
        4.5,  4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,  4.8,
        5. ,  4.5,  3.5, 13.8,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,  4.4,
        4.1,  4. ,  4.4,  nan,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,  3. ,
        4.1,  6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,  6.1,
        5.1,  5.3,  nan,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,  5.7,
        4.9,  6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,  nan,
        5.6,  5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  nan,  5.1,  5.1,
        5.9,  5.7,  nan,  5. ,  5.2,  5.4,  5.1,  4

In [16]:
petal_len = np.where(petal_len>=10,np.nan,petal_len)
petal_len

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, nan, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, nan, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, nan, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       nan, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, nan, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, nan, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, nan, 5.1, 5.1,
       5.9, 5.7, nan, 5. , 5.2, 5.4, 5.1, 4.9, 6.7, 4.9, 5.7, 6. , 4.5,
       6.3, 5.8, 5.1, 4.9, 6.7, 4.9, 6.1, 5.1, 5.3], dtype=float32)

In [17]:
med2 = np.nanmedian(petal_len)
med2

4.5

In [18]:
petal_len = np.where(np.isnan(petal_len),med2,petal_len)
petal_len

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 4.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 4.5, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 4.5, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.5, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 4.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 4.5, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 4.5, 5.1, 5.1,
       5.9, 5.7, 4.5, 5. , 5.2, 5.4, 5.1, 4.9, 6.7, 4.9, 5.7, 6. , 4.5,
       6.3, 5.8, 5.1, 4.9, 6.7, 4.9, 6.1, 5.1, 5.3], dtype=float32)

In [19]:
petal_len.dtype

dtype('float32')

petal_width

In [20]:
petal_wid = iris[1:,3] # petal width
petal_wid

array([2.000e-01, 2.000e-01, 2.000e-01, 1.020e+01, 2.000e-01, 4.000e-01,
       3.000e-01, 2.000e-01, 2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01,
       1.010e+01, 1.000e-01, 2.000e-01, 4.000e-01, 4.000e-01, 3.000e-01,
       3.000e-01, 3.000e-01, 2.000e-01, 4.000e-01, 2.000e-01, 5.000e-01,
       2.000e-01, 2.000e-01, 4.000e-01, 2.000e-01, 1.102e+02, 2.000e-01,
       2.000e-01, 4.000e-01, 1.000e-01, 2.000e-01, 1.000e-01, 2.000e-01,
       2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01, 3.000e-01, 3.000e-01,
       2.000e-01, 6.000e-01, 4.000e-01, 3.000e-01, 2.000e-01, 2.000e-01,
       2.000e-01, 2.000e-01, 1.400e+00, 1.500e+00, 1.500e+00, 1.300e+00,
       1.500e+00, 1.300e+00, 1.600e+00, 1.600e+01, 1.300e+00, 1.400e+00,
       1.000e+00, 1.500e+00, 1.000e+00, 1.400e+00, 1.300e+00, 1.400e+00,
       1.500e+00, 1.000e+00, 1.500e+00, 1.100e+00, 1.800e+00, 1.300e+00,
       1.500e+00, 1.200e+00, 1.300e+00, 1.400e+00, 1.400e+00, 1.700e+00,
       1.500e+00, 1.000e+00, 1.100e+00, 1.000e+00, 

In [21]:
petal_wid = np.where(petal_wid>=10,2,petal_wid)
petal_wid

array([0.2, 0.2, 0.2, 2. , 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 2. ,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 2. , 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 2. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 2. , 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8, 2. , 2. , 1.8, 2.1, 1.8, 1.7,
       1.8, 1.8, 1.8, 2. , 2. , 1.8, 2.5, 2. , 1.9], dtype=float32)

In [22]:
petal_wid = np.where(petal_wid==0.2,np.nan,petal_wid)
petal_wid

array([nan, nan, nan, 2. , nan, 0.4, 0.3, nan, nan, 0.1, nan, nan, 2. ,
       0.1, nan, 0.4, 0.4, 0.3, 0.3, 0.3, nan, 0.4, nan, 0.5, nan, nan,
       0.4, nan, 2. , nan, nan, 0.4, 0.1, nan, 0.1, nan, nan, 0.1, nan,
       nan, 0.3, 0.3, nan, 0.6, 0.4, 0.3, nan, nan, nan, nan, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 2. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 2. , 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8, 2. , 2. , 1.8, 2.1, 1.8, 1.7,
       1.8, 1.8, 1.8, 2. , 2. , 1.8, 2.5, 2. , 1.9], dtype=float32)

In [23]:
med3 = np.nanmedian(petal_wid)
med3

1.6

In [24]:
petal_wid = np.where(np.isnan(petal_wid),med3,petal_wid)
petal_wid

array([1.6, 1.6, 1.6, 2. , 1.6, 0.4, 0.3, 1.6, 1.6, 0.1, 1.6, 1.6, 2. ,
       0.1, 1.6, 0.4, 0.4, 0.3, 0.3, 0.3, 1.6, 0.4, 1.6, 0.5, 1.6, 1.6,
       0.4, 1.6, 2. , 1.6, 1.6, 0.4, 0.1, 1.6, 0.1, 1.6, 1.6, 0.1, 1.6,
       1.6, 0.3, 0.3, 1.6, 0.6, 0.4, 0.3, 1.6, 1.6, 1.6, 1.6, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 2. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 2. , 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8, 2. , 2. , 1.8, 2.1, 1.8, 1.7,
       1.8, 1.8, 1.8, 2. , 2. , 1.8, 2.5, 2. , 1.9], dtype=float32)

In [25]:
petal_wid.dtype

dtype('float32')

### What is the mean value of sepal length

In [26]:
np.mean(sepal_len)

5.778788

###  sort the sepal width in ascending order.

In [27]:
np.sort(sepal_wid)

array([ 2. ,  2.2,  2.2,  2.2,  2.3,  2.3,  2.3,  2.3,  2.4,  2.4,  2.4,
        2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.6,
        2.6,  2.6,  2.6,  2.7,  2.7,  2.7,  2.7,  2.7,  2.7,  2.7,  2.7,
        2.7,  2.7,  2.7,  2.7,  2.8,  2.8,  2.8,  2.8,  2.8,  2.8,  2.8,
        2.8,  2.8,  2.8,  2.8,  2.8,  2.8,  2.8,  2.8,  2.8,  2.8,  2.9,
        2.9,  2.9,  2.9,  2.9,  2.9,  2.9,  2.9,  2.9,  2.9,  2.9,  3. ,
        3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,
        3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,
        3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3. ,  3.1,
        3.1,  3.1,  3.1,  3.1,  3.1,  3.1,  3.1,  3.1,  3.1,  3.2,  3.2,
        3.2,  3.2,  3.2,  3.2,  3.2,  3.2,  3.2,  3.2,  3.2,  3.2,  3.2,
        3.2,  3.2,  3.3,  3.3,  3.3,  3.3,  3.3,  3.3,  3.3,  3.4,  3.4,
        3.4,  3.4,  3.4,  3.4,  3.4,  3.4,  3.4,  3.4,  3.4,  3.5,  3.5,
        3.5,  3.5,  3.5,  3.5,  3.6,  3.6,  3.6,  3

###  apply all statistical measures on  sepal width and length

In [28]:
np.mean(sepal_wid)

3.2169697

In [29]:
np.median(sepal_wid)

3.0

In [30]:
np.var(sepal_wid)

5.946378

In [31]:
np.std(sepal_wid)

2.4385197

In [32]:
np.max(sepal_wid)

34.0

In [33]:
np.min(sepal_wid)

2.0

In [34]:
range = np.max(sepal_wid) - np.min(sepal_wid)
range

32.0

In [35]:
np.mean(sepal_len)

5.778788

In [36]:
np.median(sepal_len)

5.8

In [37]:
np.var(sepal_len)

1.0082166

In [38]:
np.std(sepal_len)

1.0040998

In [39]:
np.max(sepal_len)

7.7

In [40]:
np.min(sepal_len)

2.0

In [41]:
range = np.max(sepal_len) - np.min(sepal_len)
range

5.7

###  after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values

In [42]:
spl_l = np.hstack((sepal_len,sepal_wid))
spl_l

array([ 5.1,  4.9,  4.7,  4.6,  2. ,  5.4,  4.6,  5. ,  4.4,  4.9,  5.4,
        4.8,  4.8,  4.3,  5.8,  5.7,  2. ,  5.1,  5.7,  5.1,  5.4,  5.1,
        4.6,  5.1,  4.8,  5. ,  5. ,  5.2,  5.2,  4.7,  4.8,  5.4,  5.2,
        5.5,  4.9,  5. ,  5.5,  4.9,  4.4,  5.1,  5. ,  4.5,  4.4,  5. ,
        5.1,  4.8,  5.1,  4.6,  5.3,  5. ,  7. ,  6.4,  6.9,  5.5,  6.5,
        5.7,  2. ,  4.9,  6.6,  5.2,  5. ,  5.9,  6. ,  6.1,  5.6,  6.7,
        5.6,  5.8,  6.2,  5.6,  5.9,  6.1,  6.3,  6.1,  6.4,  6.6,  6.8,
        6.7,  6. ,  5.7,  5.5,  5.5,  5.8,  6. ,  5.4,  6. ,  6.7,  6.3,
        5.6,  5.5,  5.5,  6.1,  5.8,  5. ,  5.6,  5.7,  5.7,  6.2,  5.1,
        5.7,  6.3,  5.8,  7.1,  6.3,  6.5,  7.6,  4.9,  7.3,  6.7,  7.2,
        6.5,  6.4,  6.8,  5.7,  5.8,  6.4,  6.5,  7.7,  7.7,  6. ,  6.9,
        5.6,  7.7,  6.3,  6.7,  7.2,  6.2,  6.1,  6.4,  2. ,  5.8,  5.8,
        6.4,  6.3,  6.1,  7.7,  6.3,  6.4,  6. ,  6.9,  6.7,  6.9,  5.8,
        6.8,  6.7,  6.7,  6.3,  6.5,  6.2,  5.9,  5

In [43]:
ptl_l = np.hstack((petal_len,petal_wid))
ptl_l

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 4.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 4.5, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 4.5, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.5, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 4.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 4.5, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 4.5, 5.1, 5.1,
       5.9, 5.7, 4.5, 5. , 5.2, 5.4, 5.1, 4.9, 6.7, 4.9, 5.7, 6. , 4.5,
       6.3, 5.8, 5.1, 4.9, 6.7, 4.9, 6.1, 5.1, 5.3, 1.6, 1.6, 1.6, 2. ,
       1.6, 0.4, 0.3, 1.6, 1.6, 0.1, 1.6, 1.6, 2. , 0.1, 1.6, 0.

In [44]:
iris1 = np.hstack((spl_l,ptl_l))

In [45]:
np.savetxt('cleaned_iris.txt',iris1)

In [46]:
np.loadtxt('cleaned_iris.txt')

array([ 5.0999999 ,  4.9000001 ,  4.69999981,  4.5999999 ,  2.        ,
        5.4000001 ,  4.5999999 ,  5.        ,  4.4000001 ,  4.9000001 ,
        5.4000001 ,  4.80000019,  4.80000019,  4.30000019,  5.80000019,
        5.69999981,  2.        ,  5.0999999 ,  5.69999981,  5.0999999 ,
        5.4000001 ,  5.0999999 ,  4.5999999 ,  5.0999999 ,  4.80000019,
        5.        ,  5.        ,  5.19999981,  5.19999981,  4.69999981,
        4.80000019,  5.4000001 ,  5.19999981,  5.5       ,  4.9000001 ,
        5.        ,  5.5       ,  4.9000001 ,  4.4000001 ,  5.0999999 ,
        5.        ,  4.5       ,  4.4000001 ,  5.        ,  5.0999999 ,
        4.80000019,  5.0999999 ,  4.5999999 ,  5.30000019,  5.        ,
        7.        ,  6.4000001 ,  6.9000001 ,  5.5       ,  6.5       ,
        5.69999981,  2.        ,  4.9000001 ,  6.5999999 ,  5.19999981,
        5.        ,  5.9000001 ,  6.        ,  6.0999999 ,  5.5999999 ,
        6.69999981,  5.5999999 ,  5.80000019,  6.19999981,  5.59

In [47]:
np.savez("cleaned_iris.npz",sepal_len,sepal_wid,petal_len,petal_wid)

In [48]:
a = np.load("cleaned_iris.npz")

In [49]:
a.files

['arr_0', 'arr_1', 'arr_2', 'arr_3']

In [50]:
a['arr_0']

array([5.1, 4.9, 4.7, 4.6, 2. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 2. , 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 2. , 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 2. ,
       5.8, 5.8, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9, 5.6, 7.7, 5.8, 5.8, 7.2, 4.9,
       7.3, 6.7, 5.9, 5.6, 7.7, 6.3, 7.2, 6.5, 6.4], dtype=float32)

In [51]:
a['arr_1']

array([ 3.5,  3. ,  3.2,  3.1,  3.6,  3. ,  3.4,  3.4,  2.9,  3.1,  3.7,
        3.4,  3. ,  3. ,  4. ,  4.4,  3. ,  3.5,  3.8,  3.8,  3.4,  3.7,
        3.6,  3.3,  3.4,  3. , 34. ,  3.5,  3.4,  3.2,  3.1,  3.4,  4.1,
        4.2,  3.1,  3.2,  3.5,  3.1,  3. ,  3.4,  3.5,  2.3,  3.2,  3.5,
        3.8,  3. ,  3.8,  3.2,  3.7,  3.3,  3.2,  3.2,  3. ,  2.3,  2.8,
        2.8,  3.3,  2.4,  2.9,  2.7,  2. ,  3. ,  2.2,  2.9,  2.9,  3.1,
        3. ,  2.7,  2.2,  2.5,  3.2,  2.8,  2.5,  3. ,  2.9,  3. ,  2.8,
        3. ,  2.9,  2.6,  2.4,  2.4,  2.7,  2.7,  3. ,  3.4,  3.1,  2.3,
        3. ,  2.5,  2.6,  3. ,  3. ,  2.3,  2.7,  3. ,  2.9,  2.9,  2.5,
        2.8,  3.3,  2.7,  3. ,  2.9,  3. ,  3. ,  2.5,  2.9,  2.5,  3.6,
        3.2,  2.7,  3. ,  2.5,  2.8,  3.2,  3. ,  3.8,  2.6,  2.2,  3.2,
        2.8,  2.8,  2.7,  3.3,  3.2,  2.8,  3. ,  2.8,  3. ,  2.8,  3.8,
        2.8,  2.8,  2.6,  3. ,  3.4,  3. ,  3. ,  3.1,  3.1,  3.1,  2.7,
        3.2,  3.3,  3. ,  2.5,  3. ,  3.4,  3. ,  2

In [52]:
a['arr_2']

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 4.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 4.5, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 4.5, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.5, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 4.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 4.5, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 4.5, 5.1, 5.1,
       5.9, 5.7, 4.5, 5. , 5.2, 5.4, 5.1, 4.9, 6.7, 4.9, 5.7, 6. , 4.5,
       6.3, 5.8, 5.1, 4.9, 6.7, 4.9, 6.1, 5.1, 5.3], dtype=float32)

In [53]:
a['arr_3']

array([1.6, 1.6, 1.6, 2. , 1.6, 0.4, 0.3, 1.6, 1.6, 0.1, 1.6, 1.6, 2. ,
       0.1, 1.6, 0.4, 0.4, 0.3, 0.3, 0.3, 1.6, 0.4, 1.6, 0.5, 1.6, 1.6,
       0.4, 1.6, 2. , 1.6, 1.6, 0.4, 0.1, 1.6, 0.1, 1.6, 1.6, 0.1, 1.6,
       1.6, 0.3, 0.3, 1.6, 0.6, 0.4, 0.3, 1.6, 1.6, 1.6, 1.6, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 2. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 2. , 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8, 2. , 2. , 1.8, 2.1, 1.8, 1.7,
       1.8, 1.8, 1.8, 2. , 2. , 1.8, 2.5, 2. , 1.9], dtype=float32)